return {
  {
    "tpope/vim-fugitive",
    -- keys = {
    --   "<leader>fb",
    --   ":Git blane<CR>",
    --   { desc = "Blame" },
    --   "<leader>fs",
    --   ":Git<CR>",
    --   { desc = "Status" },
    --   "<leader>fw",
    --   ":Git show<CR>",
    --   { desc = "Show" },
    --   "<leader>fl",
    --   ":Git log --decorate=short<CR>",
    --   { desc = "Log" },
    --   "<leader>ff",
    --   ":Git log --decorate=short -p %<CR>",
    --   { desc = "File log" },
    --   "<leader>f1",
    --   ":Git log --oneline<CR>",
    --   { desc = "Log oneline" },
    -- },
  },
}
